<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="Lukes-MacBook-Pro-3.local" name="pytest" skipped="0" tests="21" time="0.879" timestamp="2020-04-11T14:45:55.004966"><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="151" name="test_admin_admin_valid_jwt" time="0.260"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="161" name="test_admin_basic_valid_jwt" time="0.002"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="205" name="test_admin_invalid_jwt_no_authorities" time="0.002"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="171" name="test_admin_invalid_jwt_no_expires" time="0.002"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="195" name="test_admin_invalid_jwt_no_id" time="0.002"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="219" name="test_admin_invalid_jwt_no_issuedAt" time="0.001"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="183" name="test_admin_invalid_jwt_no_username" time="0.001"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="231" name="test_admin_invalid_jwt_wrong_secret" time="0.001"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="246" name="test_admin_unexpected_exception" time="0.002"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="51" name="test_basic_admin_valid_jwt" time="0.005"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="61" name="test_basic_basic_valid_jwt" time="0.003"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="105" name="test_basic_invalid_jwt_no_authorities" time="0.001"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="71" name="test_basic_invalid_jwt_no_expires" time="0.001"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="95" name="test_basic_invalid_jwt_no_id" time="0.001"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="119" name="test_basic_invalid_jwt_no_issuedAt" time="0.001"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="83" name="test_basic_invalid_jwt_no_username" time="0.001"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="131" name="test_basic_invalid_jwt_wrong_secret" time="0.001"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="146" name="test_basic_unexpected_exception" time="0.006"></testcase><testcase classname="tests.handlers.test_auth_handler.TestAuthHandler" file="tests/handlers/test_auth_handler.py" line="251" name="test_get_refresh_token" time="0.002"></testcase><testcase classname="tests.utils.test_handler_utils.TestHandlerUtils" file="tests/utils/test_handler_utils.py" line="20" name="test_no_setup_logger" time="0.001"></testcase><testcase classname="tests.utils.test_handler_utils.TestHandlerUtils" file="tests/utils/test_handler_utils.py" line="15" name="test_setup_logger" time="0.001"><failure message="AssertionError: 1 != 0">self = &lt;tests.utils.test_handler_utils.TestHandlerUtils testMethod=test_setup_logger&gt;

    def test_setup_logger(self):
        setup_logger()
        root = logging.getLogger()
&gt;       self.assertEqual(1, len(root.handlers))
E       AssertionError: 1 != 0

tests/utils/test_handler_utils.py:19: AssertionError</failure></testcase></testsuite></testsuites>